### ISSUE TITLE
File `include/servoce/math3.h` is missing

### ISSUE THREAD

**Issue by sevikkk** [Mirmik/servoce#2]
`pip install -e .` fails with error:

```
    In file included from src/pywrap.cpp:1:
    In file included from include/servoce/servoce.h:4:
    include/servoce/solid.h:5:10: fatal error: 'servoce/math3.h' file not found
```

**Comment by sevikkk** [comment]
Just removing references to it fixes problem, looks like it's actually unused.

**Comment by mirmik** [comment]
ouch...

**Comment by mirmik** [comment]
Have done.

**Comment by sevikkk** [comment]
It's not only solid.h, but some other files as well:
 include/servoce/face.h
 include/servoce/surface.h
 include/servoce/wire.h
 src/local/util.h

**Comment by mirmik** [comment]
My apologize, was inattentive.
